---
- name: Variables Demo
  hosts: g1
  become: yes
  vars: 
     myusername: Debbiemoney

  tasks:
    - name: update Dynamic page
      template:
        src: dynamic.j2
        dest: /var/www/html/dynamic.html
...